---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rh-workshops
  namespace: rh-workshops
  labels:
    app: rh-workshops
    app.kubernetes.io/name: rh-workshops
    app.kubernetes.io/part-of: rh-workshops
spec:
  selector:
    matchLabels:
      app: rh-workshops
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rh-workshops # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: rh-workshops
          imagePullPolicy: Always
          image: quay.io/kenmoini/rhgov-workshops:latest
          ports:
            - containerPort: 8080
              name: web
